context:
  version: "0.5.13"

package:
  name: litestream
  version: ${{ version }}

source:
  url: https://github.com/benbjohnson/litestream/archive/v${{ version }}.tar.gz
  sha256: 986733ce4d03e1d4a881eec8bf8597338291f505b2ebf65b0ad8da79b3ecfb34

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-cgo') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - go-licenses

tests:
  - script:
      - litestream version | grep ${{ version }}

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Streaming replication for SQLite.
  homepage: https://litestream.io/
  repository: https://github.com/benbjohnson/litestream

extra:
  recipe-maintainers:
    - asford
