context:
  version: "0.5.0"

package:
  name: litestream
  version: ${{ version }}

source:
  url: https://github.com/benbjohnson/litestream/archive/v${{ version }}.tar.gz
  sha256: 9f0c1501e54bfeeec88da6e27668e178a6a09d33b552c547526cf5cb87c23143

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-cgo') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - go-licenses

tests:
  - script:
      - litestream version | grep ${{ version }}

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Streaming replication for SQLite.
  homepage: https://litestream.io/
  repository: https://github.com/benbjohnson/litestream

extra:
  recipe-maintainers:
    - asford
